genres = {
  "__comment": "Took from http://tvtropes.org/pmwiki/pmwiki.php/Main/VideogameGenres you need to do the grouping in your script to combine the incompatible genres!",
  "genres":
  {
    "Action-Adventure": "A game that combines parts from Adventure Games and Action Games together.",
    "Metroidvania": "A game that combines parts from Adventure Action Games and Platform Games together. Features emphasis on exploring an interconnected environment and obtaining skills necessary to reach new areas of said environment.",
    "Stealth-Based Game": "A game in which the player character must hide and sneak through the level while avoiding notice from much more powerful enemies that the player character cannot take head-on.",
    "Survival Sandbox": "A game where the primary objective is to survive for as long as possible in a hostile environment. Also known as Survival Game.",
    "Survival Horror": "A game that features overwhelmed protagonist(s), oppressive atmosphere based on Horror conventions and a need for careful management of resources (ammo, health, etc.).",
    "Platform Game (Platformer)": "A game in which jumping is an important action for navigating the environment. Leaping and climbing between platforms of varying heights and over or onto enemy characters forms a large part of the gameplay.",
    "Cinematic Platform Game": "A Platform Game that portrays itself more realistically.",
    "Elimination Platformer": "A game that requires players to use the concept of jumping from one platform to another to clear the entire level of enemies.",
    "Puzzle Platformer": "A game that combines parts from Platform Games and Puzzle Games together.",
    "Run-and-Gun": "A Platformer game that borrows elements from the Shoot 'em Up genre.",
    "Beat 'em Up": "A Sub-genre of Action Game with the player character fighting primarily with punches and kicks against against large hordes of relatively weaker enemies.",
    "Hack and Slash": "A Beat 'em Up game where the player character primarily wields close range melee weaponry, like a sword or axe.",
    "Stylish Action": "A Beat 'em Up or Hack and Slash game based around fighting enemies as stylishly and/or efficiently as possible.",
    "Fighting Game": "An Action Game that is primarily about one-on-one fights between two (or rarely more) equally skilled opponents.",
    "Mascot Fighter": "Ultimate Showdown Of Ultimate Destiny is heavily featured.",
    "Platform Fighter": "A fighting game combined with platform game elements; has great emphasis on maneuverability on dynamic stages.",
    "First-Person Shooter (FPS)": "A game in which the perspective is through the eyes of the player character, and the action revolves around shooting.",
    "Hero Shooter": "A Sub-genre of FPS games in which each character has different abilities and weapons.",
    "Light Gun Game": "A game in which the player has a pointing device that resembles a gun and points it at the screen to shoot on-screen enemies.",
    "Rail Shooter": "A game in which the computer controls most of your movement and you control the shots.",
    "Shoot 'em Up (Shmups)": "A fixed-scrolling shooting game that is not three-dimensional.",
    "Bullet Hell": "A vertically scrolling shooter game that has every single enemy fire hundreds or thousands of projectiles on-screen at once at the player character, testing their dodging skills.",
    "Cute 'em Up": "A Shoot Em Up game that casts the enemies as cute things such as kittens, candy, fairies, and so on.",
    "Horizontal Scrolling Shooter": "A Shoot Em Up game that has a horizontal Auto-Scrolling Level, that is, to the left or right.",
    "Vertical Scrolling Shooter": "A Shoot Em Up game that has a vertical Auto Scrolling Level, that is, up or down.",
    "Tactical Shooter": "A First/Third-person shooter game that simulates realistic combat, encouraging use of real-life combat tactics. Key gameplay mechanics include realistically damaging bullets, Squad Controls, Subsystem Damage, cover mechanics, situational awareness aids, mission planning, et cetera.",
    "Third-Person Shooter (3PS/TPS)": "A 3D game that has the camera looking behind the player character or over their shoulder, and involves the use guns and similar weapons.",
    "Vehicular Combat": "A game that has the player control a normally armed motor vehicle and must destroy all enemies.",
    "Environmental Narrative Game": "A story-driven adventure game which emphasizes narrative and exploring a physical location, with very little in the way of interactivity or gameplay challenge. Also known by other labels including 'walking simulator', 'story exploration game' and 'interactive stories'.",
    "Full Motion Video (Interactive Movie)": "A game that is based around video clips, and the player must press buttons at the right time, choose the right sequence of clips, or play other games using the video as a backdrop.",
    "Interactive Fiction": "An Adventure Game in which the interaction is almost entirely text-based.",
    "Point-and-Click Game": "A game in which player interacts with the environment by moving the mouse cursor over areas of the screen and clicking on them.",
    "Room Escape Game": "A simplistic type of Point-and-Click Game consisting solely of puzzles to escape a room or series of rooms.",
    "Romance Game": "A game in which the primary goal is to establish a romantic relationship between the Player Character and one or more of the NPCs.",
    "Dating Sim": "A game in which the player courts at least one potential lover, and the player must keep track of every character's feelings about them and giving out presents, which will feel like a Role Playing Game.",
    "Visual Novel": "Even though people equate this with 'Dating Sim' they are not the same. Unlike Dating Sims, Visual Novels are more like Adventure Games that allow you to choose your own adventure and get different endings based off of your choices.",
    "Breaking Out": "A game in which a paddle at the bottom of the screen bounces a ball to destroy blocks, and missing the ball results in the player losing a life.",
    "Card Battle Game": "A game in which players brings their own deck of cards to play.",
    "Casual Video Game": "A game that is easy to learn and relatively simple by design.",
    "Endless Running Game": "A game about enduring an endless sequence of obstacles as long as possible.",
    "Exergaming": "A game that encourages the player to exercise and to get into shape.",
    "Hidden Object Game": "A game in which there is a photorealistic cluttered scene and the player must find and click on a series of objects in it.",
    "Match-Three Game": "A game in which the player must match three objects of similar color/shape/species to eliminate said objects from the playing field.",
    "Minigame Game": "A game that has a series of puzzles, challenges and games with very different requirements for defeating them.",
    "Party Game": "A Minigame Game in which two to four players compete against each other in a boardgame-like environment.",
    "Virtual Paper Doll": "A game that is about customizing a character's appearance.",
    "Digging Game": "A game in which the player digs through terrain while minding falling objects.",
    "Digital Pinball Tables": "Computerized pinball game whether replicas of Physical Pinball Tables or original boards with features that can only exist in software.",
    "Edutainment Game": "A game that educates players as well as entertains them.",
    "Escort Game": "A game about escorting someone.",
    "Idle Game": "A genre of game defined by its gameplay, the primary feature of which is that the easiest way to win is to leave the game running by itself for long periods of time.",
    "Mad Marble Maze": "A game in which the player rolls a round object of some kind from the beginning to the end of a level.",
    "Maze Game ": "A game that takes place in a maze, and the player must either get from one side of the maze to the other, or clear it of every item that won't kill the player.",
    "Multiplayer Online Battle Arena (MOBA)": "A game that has teams of players competing with each other, typically using the point-and-click interface of a Real Time Strategy; but, unlike RTS games, players control only one Hero Unit instead of a military-industrial complex.",
    "Pop Up Video Games": "A game in which clicking on background items results in cute animations.",
    "Programming Game": "A game in which the player has little to no direct control over the game's events, and must set up the solution, then hit a 'go' switch to activate the solution and see if it accomplishes the task correctly.",
    "Puzzle Game": "A game that requires mental skill as well as, or instead of, dexterity and quick reflexes.",
    "Bizarre Puzzle Game": "A Puzzle Game that is so weird and mind-defying that trying to label it with a genre is a puzzle in and of itself.",
    "Teamwork Puzzle Game": "A game in which the player controls a group of characters, and progress frequently depends on puzzles making use of this fact.",
    "Falling Blocks": "A game in which blocks fall from the top of the screen, requiring the player to move and flip them so that they'll be arranged in a way to make them disappear, and if the blocks reach the top of the screen then the game ends.",
    "Racing Game": "A game in which the player drives a vehicle of some kind and races against either other players or time.",
    "Mascot Racer": "A game with colorful characters use colorful weapons in their races.",
    "Rising Up The Food Chain Game": "A game in which the player must eat creatures smaller than himself and become bigger, which allows him to eat more creatures.",
    "Rhythm Game": "A game that will flash commands, and the player has to input the same, synchronized to a beat or melody.",
    "Role-Playing Game (RPG) — see also Tabletop Games (Tabletop RPG)": "A game in which the player controls a character or party of characters in a statistically abstracted way.",
    "Action RPG": "A game that combines parts from Role Playing Games and Action Adventure Games together. Either a sub-genre of the Role-playing Game or a genre modifier, depending on who you ask.",
    "Eastern RPG": "A usually Japanese game that tends to have a linear plot and a party of pre-defined characters written into said plot.",
    "Multi-User Dungeon (MUD) and MOO": "An Interactive Fiction game that allows multiple (perhaps thousands) players to play at the same time.",
    "Massively Multiplayer Online Role-Playing Game (MMORPG)": "A game that has hundreds of players interacting with each other in the same world in real-time, which completing quests and leveling up.",
    "MUCK": "A Multi-User Text-Oriented Game that emphasizes roleplaying and player intervention.",
    "MUSH (Multi User Shared Hallucination)": "A MUD game that is just a series of rooms, with players given the bare minimum of interaction systems and let loose to create and manage their own roleplaying.",
    "Roguelike": "A game that features Dungeon Crawling with randomly-generated environments randomly stocked from a huge list of monsters and items, Final Death, Anti-Grinding and is Nintendo Hard.",
    "Strategy RPG (SRPG)": "A game that is a Role Playing Game, but it plays like a Turn Based Strategy or Real Time Strategy.",
    "Western RPG": "A North American or European game that features a customizable featureless protagonist.",
    "Simulation Game (Sim)": "A game that simulates parts of a reality, fictional or real.",
    "Construction and Management Games": "This type of game focuses on elements like gathering and management of resources, construction, expansion, research and exploration.",
    "Driving Game": "A game in which the player drives a vehicle of some kind. Racing Game and Vehicular Combat are sub-genres where competition with other drivers becomes a major focus.",
    "Immersive Sim": "A game that simulates a consistent lived-in world, facilitates Emergent Gameplay, and rewards creative problem solving.",
    "Life Simulation Game": "A game in which the player plays as, or at least has control over the lives, of living beings and goes through their life.",
    "Raising Sim": "A game in which schedules for a game to process are applied, which in turn affects characters in the game, who then develop 'on their own' without constant user interference.",
    "Virtual Pet": "A game where the player interacts with a digital pet, with the goal of caring for it like a real one.",
    "Sports Game": "A game that simulates playing a traditional physical sport.",
    "Wrestling Game": "A game that simulates Professional Wrestling, with grapples, holds and throws.",
    "Strategy Game": "A game in which the player's strategical and/or tactical thinking is required in order to achieve victory.",
    "4X (4X)": "A game that has four simple goals, which are eXplore, eXpand, eXploit and eXterminate. Sub-genre of a Strategy Game.",
    "Artillery Game": "A game that tasks the player with successfully aiming at an opponent with a ballistics trajectory under various conditions.",
    "Real-Time Strategy (RTS)": "A game that focuses on construction and control of a fighting force in battle that takes place in real-time.",
    "Space-Management Game": "A game in which the player must figure out how to make the most out of as little space as possible.",
    "Time Management Game": "A game in which the player must perform task such as serving food and changing baby's diapers as fast as possible.",
    "Tower Defense": "A game in which the player defends a building from monsters using other buildings, sometimes with a unit or two as back-up.",
    "Turn-Based Strategy (TBS)": "A game that is about abstract mechanics of efficiently waging war, exploiting resources and controlling huge groups of combatants all at once.",
    "Turn-Based Tactics": "A game in which the player must control individual soldiers or vehicles."
  }
}

